### ISSUE TITLE
Does this work consider electrical power substations?

### ISSUE THREAD

**Issue by Avv22** [igbe/DNP3#1]
Hello Mr Igbe,

Thank you for offering the datasets. Does this dataset include electrical power substation?
 
Thank you.

**Comment by igbe** [comment]
Hi Ibra,

This work was done using the OpenDNP3 software that is available online and
we simulated the effects that an actual attack would have using the slave
and master demo configs (modified the demo that come with the OpenDNP3).

So in summary, no we didn’t connect this to an actual electrical power
substations. See the paper linked to that dataset for explanation of the
setup.
